; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects
projects[drupal][version] = "7.22"

projects[apachesolr][subdir] = "contrib"
projects[apachesolr][version] = "1.3"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.7"

projects[coder][subdir] = "contrib"
projects[coder][version] = "2.0-beta2"

projects[ckeditor_link][subdir] = "contrib"
projects[ckeditor_link][version] = "2.3"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"

projects[context][subdir] = "contrib"
projects[context][version] = "3.0-beta6"

projects[context_filter][subdir] = "contrib"
projects[context_filter][version] = "1.x-dev"

projects[context_inline_editor][subdir] = "contrib"
projects[context_inline_editor][version] = "1.x-dev"
projects[context_inline_editor][patch][0] = "http://drupal.org/files/filter_context_1327672-5.patch"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[danishstemmer][subdir] = "contrib"
projects[danishstemmer][version] = "1.1"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[delta][subdir] = "contrib"
projects[delta][version] = "3.0-beta11"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

projects[devel_themer][subdir] = "contrib"
projects[devel_themer][version] = "1.x-dev"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.1"

projects[facetapi][subdir] = "contrib"
projects[facetapi][version] = "1.3"

projects[fb_social][subdir] = "contrib"
projects[fb_social][version] = "2.0-beta4"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0-rc1"

projects[features_override][subdir] = "contrib"
projects[features_override][version] = "2.0-beta2"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-alpha8"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-unstable7"

projects[flexslider][subdir] = "contrib"
projects[flexslider][version] = "1.0-rc3"
projects[flexslider][patch][0] = "http://drupal.org/files/flexslider-updated_make_file_with_correct_version_flexslider_library-1736474-5.patch"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.3"

projects[html5_tools][subdir] = "contrib"
projects[html5_tools][version] = "1.2"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.3"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "1.0-beta3"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"

projects[link][subdir] = "contrib"
projects[link][version] = "1.1"

projects[linkit][subdir] = "contrib"
projects[linkit][version] = "2.6"

projects[location][subdir] = "contrib"
projects[location][version] = "3.0-rc2"

projects[mailchimp][subdir] = "contrib"
projects[mailchimp][version] = "2.10"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-unstable7"

projects[mediaelement][subdir] = "contrib"
projects[mediaelement][version] = "1.2"

projects[media_vimeo][subdir] = "contrib"
projects[media_vimeo][version] = "1.0-beta5"

projects[media_youtube][subdir] = "contrib"
projects[media_youtube][version] = "2.0-rc3"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.3"

projects[memcache][subdir] = "contrib"
projects[memcache][version] = "1.0"

projects[menu_position][subdir] = "contrib"
projects[menu_position][version] = "1.1"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0-beta7"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.7"

projects[multiform][subdir] = "contrib"
projects[multiform][version] = "1.0"

projects[nanosoap][subdir] = "contrib"
projects[nanosoap][version] = "1.0"

projects[nodespotbox][subdir] = "contrib"
projects[nodespotbox][version] = "1.7"

projects[omega_tools][subdir] = "contrib"
projects[omega_tools][version] = "3.0-rc4"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.3"

projects[page_title][subdir] = "contrib"
projects[page_title][version] = "2.7"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[pathologic][subdir] = "contrib"
projects[pathologic][version] = "2.10"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[scheduler][subdir] = "contrib"
projects[scheduler][version] = "1.1"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.1"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.0"

projects[webform][subdir] = "contrib"
projects[webform][version] = "3.19"

projects[workbench][subdir] = "contrib"
projects[workbench][version] = "1.2"

projects[workbench_files][subdir] = "contrib"
projects[workbench_files][version] = "1.0"

projects[workbench_media][subdir] = "contrib"
projects[workbench_media][version] = "1.1"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"
projects[wysiwyg][patch][0] = "http://drupal.org/files/746524-143-D7.patch"

projects[omega][type] = "theme"
projects[omega][version] = "3.1"

projects[itkore][type] = "theme"
projects[itkore][download][type] = "git"
projects[itkore][download][url] = "git@github.com:aakb/itkore.git"

projects[itkore_features][type] = "module"
projects[itkore_features][download][type] = "git"
projects[itkore_features][download][url] = "git@github.com:aakb/itkore_features.git"

; Libraries
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.0.1.1/ckeditor_4.0.1.1_full.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][destination] = "libraries"

libraries[tinymce][download][type] = "get"
libraries[tinymce][download][url] = "https://github.com/downloads/tinymce/tinymce/tinymce_3.4.2.zip"
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][destination] = "libraries"

libraries[jquery.cycle][download][type] = "get"
libraries[jquery.cycle][download][url] = "https://raw.github.com/malsup/cycle/master/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][destination] = "libraries"

libraries[autopager][download][type] = "get"
libraries[autopager][download][url] = "http://jquery-autopager.googlecode.com/files/jquery.autopager-1.0.0.js"
libraries[autopager][directory_name] = "autopager"
libraries[autopager][destination] = "libraries"

